# Generated by Django 3.0.4 on 2020-04-01 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='대표 학생')),
                ('place', models.CharField(max_length=15, verbose_name='위치')),
                ('num_people', models.IntegerField(default=1)),
                ('purpose', models.TextField()),
                ('demand_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_time', models.DateTimeField()),
            ],
        ),
    ]
